### ISSUE TITLE
Indentation

### ISSUE THREAD

**Issue by MaGOs92** [Eline31/Projet_2#2]
Je vois que l'indentation du fichier n'est pas parfaite. Est-ce que tu as le plugin "Prettier" installé dans ton VSCode?

https://github.com/Eline31/Projet_2/blob/d814896b83ca89bc6ce44f21cddc04064afe5bd8/index.html#L1

**Comment by Eline31** [comment]
Je ne l'avais pas, mais c'est bon c'est installé et utilisé !
