### ISSUE TITLE
Variables CSS inutilisées 

### ISSUE THREAD

**Issue by MaGOs92** [Eline31/Projet_2#4]
Très bien d'avoir défini des variables CSS, mais je ne vois pas où est utilisé --lightblue et --animation.

https://github.com/Eline31/Projet_2/blob/d814896b83ca89bc6ce44f21cddc04064afe5bd8/css/styles.css#L12

**Comment by Eline31** [comment]
j'ai effectivement ajouté le lightblue, pour ce qui est de l'animation il faut que je vois d'abord ce que c'est, mon mentor m'avait dit de le mettre dans le code mais je n'en connais pas la fonction, donc je regarde !
